version: '3'
services:
  db:
    image: mysql
    container_name: ps-mysql # 容器名
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xrxy0852!!! #root管理员用户密码
      MYSQL_USER: limeschool   #创建test用户
      MYSQL_PASSWORD: limeschool!!!  #设置test用户的密码
    ports:
      - '3307:3306'  #host物理直接映射端口为6606
    volumes:
      - "./data/db:/var/lib/mysql"
      - "./data/conf:/etc/mysql/conf.d"



