version: "3"
services:
  redis:
    restart: always
    image: redis
    hostname: redis
    container_name: ps-redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/conf/redis.conf:/etc/redis.conf
      - ./redis/data:/data:rw
      - ./redis/logs:/logs:rw
    command:
      redis-server /etc/redis.conf
